# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X < Formula
  desc "a simple and fast task runner"
  homepage "https://github.com/bambamboole/x"
  version "0.1.0-rc4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bambamboole/x/releases/download/0.1.0-rc4/x-0.1.0-rc4-darwin-amd64"
      sha256 "841a12e8558fd0d4b2145f35a17c678bca12abf1c7dc2f38f835c1d6d8aaf40f"

      def install
        bin.install "x-0.1.0-rc4-darwin-amd64" => "x"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bambamboole/x/releases/download/0.1.0-rc4/x-0.1.0-rc4-darwin-arm64"
      sha256 "8754a237441c5df88d626979d2cc12e123b6b50209575f2abd471f9207ab54c0"

      def install
        bin.install "x-0.1.0-rc4-darwin-arm64" => "x"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bambamboole/x/releases/download/0.1.0-rc4/x-0.1.0-rc4-linux-arm64"
      sha256 "676e0a57c148939161c2f03aaceb9b4a1ce84b77c0340cad298f005b979909c8"

      def install
        bin.install "x-0.1.0-rc4-linux-arm64" => "x"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bambamboole/x/releases/download/0.1.0-rc4/x-0.1.0-rc4-linux-amd64"
      sha256 "4a5d7bbf4088bb67628d20dd6e2694ea944714cd69f00e79e49c00ca04266500"

      def install
        bin.install "x-0.1.0-rc4-linux-amd64" => "x"
      end
    end
  end
end
