name: Release

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, darwin]
        arch: [arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
      - name: Download & verify dependencies
        run: go mod download && go mod verify
      - name: Build
        run: CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} go build -o x cmd/main/main.go

