name: Release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOs-latest]
        arch: [amd64, arm64]
        include:
          - os: ubuntu-latest
            goos: linux
          - os: macOs-latest
            goos: darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
      - name: Download & verify dependencies
        run: go mod download && go mod verify
      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} go build -o x cmd/main/main.go
